
DROP TABLE t_anuncio CASCADE CONSTRAINTS;
DROP TABLE t_associacao CASCADE CONSTRAINTS;
DROP TABLE t_associacao2 CASCADE CONSTRAINTS;
DROP TABLE t_campanha CASCADE CONSTRAINTS;
DROP TABLE t_cidade CASCADE CONSTRAINTS;
DROP TABLE t_cliente CASCADE CONSTRAINTS;
DROP TABLE t_email CASCADE CONSTRAINTS;
DROP TABLE t_empresa CASCADE CONSTRAINTS;
DROP TABLE t_fonte_dados CASCADE CONSTRAINTS;
DROP TABLE t_ia CASCADE CONSTRAINTS;
DROP TABLE t_pais CASCADE CONSTRAINTS;
DROP TABLE t_previsao_tendencia CASCADE CONSTRAINTS;
DROP TABLE t_regiao CASCADE CONSTRAINTS;
DROP TABLE t_resultado CASCADE CONSTRAINTS;


DROP SEQUENCE seq_anuncio;
DROP SEQUENCE seq_associacao;
DROP SEQUENCE seq_associacao2;
DROP SEQUENCE seq_campanha;
DROP SEQUENCE seq_cidade;
DROP SEQUENCE seq_cliente;
DROP SEQUENCE seq_email;
DROP SEQUENCE seq_empresa;
DROP SEQUENCE seq_fonte_dados;
DROP SEQUENCE seq_ia;
DROP SEQUENCE seq_pais;
DROP SEQUENCE seq_previsao_tendencia;
DROP SEQUENCE seq_regiao;
DROP SEQUENCE seq_resultado;


